#
# Install and configure Mesos-DNS
#

- name: Remove package no needed
  apt: pkg="bind9" state=absent
  tags:
    - packages

- name: Copy Mesos DNS tarball
  copy: src=mesos-dns.tar dest=/tmp/mesos-dns.tar
  when: "'mesos-dns' in group_names"
  tags:
    - configuration

- name: Extracting mesos-dns tarball
  unarchive: src=/tmp/mesos-dns.tar dest=/usr/bin copy=no
  when: "'mesos-dns' in group_names"
  tags:
    - configuration

- name: Create mesos-dns configuration directory
  file: path="/etc/opt/mesos-dns" state=directory recurse=yes

- name: Copy configuration file for Mesos DNS
  template: src=config.json.j2 dest="/etc/opt/mesos-dns/config.json"
  when: "'mesos-dns' in group_names"
  tags:
    - configuration

- name: Copy mesos-dns.service file
  template: src=mesos-dns.service.j2 dest="/lib/systemd/system/mesos-dns.service"
  when: "'mesos-dns' in group_names"
  tags:
    - configuration

- name: Start Mesos-DNS service
  service: name=mesos-dns state=started
  when: "'mesos-dns' in group_names"

- name: Remove name server dns IP addresses if it exists
  lineinfile: dest=/etc/resolv.conf state=absent regexp="nameserver {{hostvars[item]['ansible_eth0']['ipv4']['address']}}"
  with_items: "{{groups['mesos-dns']}}"
  tags:

- name: Add name server dns IP addresses
  lineinfile: dest=/etc/resolv.conf insertbefore=BOF line="nameserver {{hostvars[item]['ansible_eth0']['ipv4']['address']}}"
  with_items: "{{groups['mesos-dns']}}"
  tags:

- name: Make the resolv.conf file permanent
  command: chattr +i /etc/resolv.conf
  tags:
