# tasks/install.yml

# Install and configure remote CFSSL server
---
- name: Create pki directory
  file: path=/srv/pki state=directory recurse=yes

- name: Copy intermediate ca
  template: src=internal-ca.pem.j2 dest=/srv/pki/internal-ca.pem mode=0600
  no_log: true

- name: Copy intermediate ca key
  template: src=internal-ca-key.pem.j2 dest=/srv/pki/internal-ca-key.pem mode=0600
  no_log: true

- name: Copy internal ca configuration file
  copy: src=config_internal-ca.json dest=/srv/pki/config_internal-ca.json

- name: Copy internal-ca.service file
  copy: src=internal-ca.service dest=/lib/systemd/system/internal-ca.service

- name: Run cfssl service
  service: name=internal-ca state=started

- name: Waiting for cfssl port to become available
  wait_for: port=8888 delay=10
