#
# Handlers file for the Mesos installation
# and configuration.
#

## Mesos master handlers
- name: Start mesos-master
  service: name=mesos-master state=started

- name: Restart mesos-master
  service: name=mesos-master state=restarted

- name: Stop mesos-master
  service: name=mesos-master state=stopped
  
## Mesos slave handlers
- name: Start mesos-slave
  service: name=mesos-slave state=started

- name: Restart mesos-slave
  service: name=mesos-slave state=restarted

- name: Stop mesos-slave
  service: name=mesos-slave state=stopped