#
# Marathon role variables
#

# Definition of the JAVA_HOME path
marathon_java_home_path: "/usr/lib/jvm/java-8-openjdk-amd64/"

# Definition of the JAVA_OPTS
marathon_java_opts_var: "-Xmx512m"

# Definition of the HTTP port of marathon
marathon_http_port: "8080"

# Definition of the High Availability mode
marathon_high_availability_mode: "true"

marathon_secret_dir: /srv/marathon

marathon_secret_file: "{{marathon_secret_dir}}/credential"

marathon_principal: "Fake"

marathon_secret: "toto"
