#
# Marathon role variables
#

# Definition of the JAVA_HOME path
marathon_java_home_path: "/usr/lib/jvm/java-8-openjdk-amd64/"

# Definition of the JAVA_OPTS
marathon_java_opts_var: "-Xmx512m"

# Definition of the HTTP port of marathon
marathon_http_port: "8080"

# Definition of the High Availability mode
marathon_high_availability_mode: "true"

# Marathon framework credential directory
marathon_credential_dir: /srv/mesos/framework/marathon

# Marathon framework credential file
marathon_credential_file: "{{marathon_credential_dir}}/credential"

# Definition of the Marathon libprocess ip
marathon_libprocess_ip: "{{ansible_eth0.ipv4.address}}"
