---
language: python
python: "2.7"

services:
    - docker

install:
  # Build Ansible image
  - cd ansible; docker build -t ansible-test .

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i hosts.localhost install.yml --syntax-check

  # Run Ansible testing playbook
  - docker run --privileged -t ansible-test
