---
language: python
python: "2.7"

services:
    - docker

install:
  # Build Ansible image
  - cd ansible; docker build -t ansible-test .

script:
  # Run Ansible testing playbook
  - docker run --privileged -t ansible-test
