---
language: python
python: "2.7"

services:
  - docker

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install ansible
  - pip install ansible

  # Build Ansible image
  - cd ansible; docker build -t ansible-test .

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i hosts.localhost install.yml --syntax-check

  # Run Ansible testing playbook
  - docker run --privileged -t ansible-test
