#
# Configure and install telegraf
#

- name: Unarchive telegraf binary
  unarchive: src=telegraf_linux_amd64_0.2.3.tar.gz dest=/usr/local/bin
  tags:
    - configuration

- name: Prepare telegraf configuration directory
  file: path=/etc/opt/telegraf state=directory recurse=yes
  tags:
    - configuration

- name: Copy telegraf systemd service configuration
  copy: src=telegraf.service dest=/lib/systemd/system/telegraf.service
  tags:
    - configuration

- name: Copy telegraf configuration file
  template: src=default.conf.j2 dest=/etc/opt/telegraf/default.conf
  tags:
    - configuration

- name: Start telegraf service
  service: name=telegraf state=started
