#
# Elasticsearch Dockerfile
#

FROM elasticsearch:2.0

MAINTAINER Lucien Zagabe <rz@ognitio.com>

ADD conf/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
WORKDIR /usr/share/elasticsearch/data
