#
# Update the hostname.
#

- name: Update the hostname
  template: src=hostname.j2 dest=/etc/hostname owner=root group=root mode=0644
  sudo: yes

- name: Update IPv4 hostname /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "^127.0.0.1"
    line: "127.0.0.1{{'\t'}}{{var_hostname}}{{'\t'}}localhost{{'\t'}}localhost.localdomain{{'\n'}}"

- name: Update IPv6 hostname /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "^::1"
    line: "::1{{'\t'}}{{var_hostname}}{{'\t'}}localhost{{'\t'}}ip6-localhost{{'\t'}}ip6-loopback"

- name: Restart remote hosts
  command: shutdown --no-wall -r +1 "Ansible updates triggered"
  when: local != "true"
  
- name: Reloading network configuration (waiting 1m20s)
  pause: seconds=80
