#
# Install or test Apache Mesos
#

- include: testing.yml
  when: playbook_mode == "testing"

- include: install.yml
  when: playbook_mode == "install"

- include: upgrade.yml
  when: playbook_mode == "upgrade"