# tasks/main.yml

# Install or test Apache Mesos
---
- include: test.yml
  when: playbook_mode == "test"

- include: install.yml
  when: playbook_mode == "install"

- include: upgrade.yml
  when: playbook_mode == "upgrade"