# tasks/main.yml

# Apache Mesos role
---
- include: test.yml
  when: playbook_mode == "test"

- include: install.yml
  when: playbook_mode == "install"

- include: upgrade.yml
  when: playbook_mode == "upgrade"