#
# Configure and deploy registry-proxy
#

- name: Install nginx package
  apt: pkg=nginx state=present update_cache=yes
  tags:
    - packages

- name: Stop nginx service
  service: name=nginx state=stopped

- name: Copy nginx wrapper
  copy: src=registry-proxy dest=/usr/sbin/registry-proxy mode=0755

- name: Copy registry-proxy service file
  copy: src=registry-proxy.service dest=/lib/systemd/system/registry-proxy.service

- name: Copy Dockerfile
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  tags:
    - configuration

- name: Start registry-proxy service
  service: name=registry-proxy state=started
