#
# Weave network isolation configuration
#

# IMPORTANT: This step is quite unsage we might think about undertaking a
# different approach to download and run the weave script.
- name: Download weave script
  get_url: url=http://git.io/weave dest=/usr/local/bin/weave mode=0755

- name: Create the weave bridge
  command: weave create-bridge
  environment:
    WEAVE_NO_FASTDP: 1

- name: Expose weave bridge to the host
  command: ip addr add dev weave {{weave_bridge_cidr}} # e.g. 10.2.0.2/16

- name: Restart service docker
  service: name=docker state=restarted

# Connect to existing network
- name: Launch weave and connect to existing network
  command: weave launch {{hostvars[weave_network]['ansible_eth0']['ipv4']['address']}}
  when: weave_network is defined
  environment:
    WEAVE_NO_FASTDP: 1

- name: Launch weave
  command: weave launch
  when: weave_network is undefined
  environment:
    WEAVE_NO_FASTDP: 1

- name: Edit mesos-slave environment 1/1
  lineinfile:
    dest=/etc/default/mesos-slave
    line='export MESOS_DOCKER_SOCKET="/var/run/weave/weave.sock"'

- name: Edit mesos-slave environment 2/2
  lineinfile:
    dest=/etc/default/mesos-slave
    line='export MESOS_EXECUTOR_ENVIRONMENT_VARIABLES="{\\"DOCKER_HOST\\":\\"unix:///var/run/weave/weave.sock\\"}"'

- name: Restart mesos-slave service
  service: name=mesos-slave state=restarted
