#
# Install and configure Marathon
#

- name: Add jessie-backports repo
  apt_repository: repo="deb http://http.debian.net/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}}-backports main" state=present

- name: Installation of open-jdk-8 and Marathon
  apt: name={{item}} update_cache=yes
  with_items:
    - openjdk-8-jre-headless
    - marathon

#- name: Remove default configuration file
#  file: path={{item}} state=absent
#  with_items:
#    - "/etc/default/marathon"
#    - "/etc/syslog-ng/conf.d/marathon.conf"
#    - "/tmp/marathon_check.sh"
    
- name: Copy default marathon configuration file
  template: src=default_marathon_conf.j2 dest=/etc/default/marathon

- name: Copy syslog configuration file
  copy: src=syslog-marathon.conf dest=/etc/syslog-ng/conf.d/marathon.conf

- name: Create mesos credentials directory
  file: path="{{marathon_secret_dir}}" recurse=yes state=directory
  
- name: Copy mesos authentication secret
  template: src=mesos_authentication_secret.j2 dest="{{marathon_secret_file}}" mode=0600
  no_log: true
  
- name: Start marathon
  service: name=marathon state=started
