#
# Install and configure Marathon
#

- name: Add jessie-backports repo
  apt_repository: repo="deb http://http.debian.net/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}}-backports main" state=present
  tags:
    - configuration

- name: Installation of open-jdk-8 and Marathon
  apt: name={{item}} update_cache=yes
  with_items:
    - openjdk-8-jre-headless
    - marathon
  register: job_result
  until: job_result|success
  retries: 3
  tags:
    - configuration

- name: Create sysconfig directory
  file: path=/etc/sysconfig state=directory recurse=yes
  tags:
    - configuration
    
- name: Copy marathon configuration file
  template: src=default_marathon_conf.j2 dest=/etc/sysconfig/marathon
  tags:
    - configuration

- name: Create marathon logging directory
  file: path=/var/log/marathon state=directory recurse=yes
  tags:
    - configuration
  
- name: Copy syslog configuration file
  copy: src=syslog-marathon.conf dest=/etc/syslog-ng/conf.d/marathon.conf
  notify: Restart syslog-ng
  tags:
    - configuration

- name: Create marathon credential directory
  file: path="{{marathon_credential_dir}}" state=directory recurse=yes
  when: mesos_credentials is defined
  tags:
    - configuration
  
- name: Create marathon authentication credential file
  template: src=marathon_credential.j2 dest="{{marathon_credential_file}}" mode=0600
  no_log: true
  when: mesos_credentials is defined
  tags:
    - configuration
  
- name: Start marathon
  service: name=marathon state=started
