#
# Install and configure Marathon
#

- name: Add jessie-backports repo
  apt_repository: repo="deb http://http.debian.net/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}}-backports main" state=present

- name: Installation of open-jdk-8 and Marathon
  apt: name={{item}} update_cache=yes
  with_items:
    - openjdk-8-jre-headless
    - marathon

- name: Remove existing configuration file
  file: path={{item}} state=absent
  with_items:
    - "/etc/sysconfig/marathon"
    - "/etc/syslog-ng/conf.d/marathon.conf"
    - "/tmp/marathon_check.sh"

- name: Create sysconfig directory
  file: path=/etc/sysconfig state=directory recurse=yes
    
- name: Copy marathon configuration file
  template: src=default_marathon_conf.j2 dest=/etc/sysconfig/marathon

- name: Copy syslog configuration file
  copy: src=syslog-marathon.conf dest=/etc/syslog-ng/conf.d/marathon.conf

- name: Create marathon credential directory
  file: path="{{marathon_credential_dir}}" state=directory recurse=yes
  
- name: Create marathon authentication credential file
  template: src=marathon_credential.j2 dest="{{marathon_credential_file}}" mode=0600
  no_log: true
  
- name: Start marathon
  service: name=marathon state=started
