- name: Hosts default configuration
  hosts: all
  any_errors_fatal: true
  sudo: yes
  vars:
    local: "true"
    test: "{{ testing }}"
  roles:
    - hostname
    - users
    - sudoers
    - apt
    - debian-auto-upgrade
