- name: Hosts default configuration
  hosts: all
  any_errors_fatal: true
  sudo: yes
  vars:
    local: "true"
    test: "{{ testing }}"
  roles:
    - hostname
    - users
    - sudoers
    - apt
    - debian-auto-upgrade

- name: Apache Zookeeper
  hosts: zookeeper
  any_errors_fatal: true
  sudo: yes
  vars:
    test: "{{ testing }}"
    zookeeper_standalone: true
  roles:
    - zookeeper
