#
# Install necessary packages
#

- name: Install requirements
  apt: pkg={{item}} state=present update_cache=yes
  with_items: apt_packages

- name: Copy checking script
  copy: src=check_apt.sh dest=/tmp/

- name: Set execution right for the script
  file: path=/tmp/check_apt.sh mode=0744

- name: Checking the packages installed
  command: "/tmp/check_apt.sh {% for pkgs in apt_packages %}{{pkgs}} {% endfor %}"
  ignore_errors: no
