# defaults/main.yml

# Mesos automation role variables.
---
# General configuration
# Definition of the ULIMIT of the process
mesos_ulimit: "-n 8191"

# Definition of the working directory
mesos_work_dir: /var/lib/mesos

# Definition of the mesos IP address
mesos_ip_address: "{{ansible_eth0.ipv4.address}}"


# Mesos master configuration
# Definition of the quorum
mesos_master_quorum: 2

# Definition of the master port
mesos_masters_port: 5050


## Mesos slave configuration
# Definition of the slave port
mesos_slaves_port: 5051

# Definition of the CPUs resources
mesos_slaves_cpus: 4.0

# Definition of the RAM resources (MB)
mesos_slaves_mem: 3200

# Definition of the disk space
mesos_slaves_disk: 40000

# Definition of the min port
mesos_slaves_min_port: 21000

# Definition of the max port
mesos_slaves_max_port: 24000

# Definition mesos slaves OS
mesos_slaves_os: "{{ansible_distribution|lower}}-{{ansible_distribution_release}}"

# Definition of the service provider
mesos_slave_service_provider: "kimsufi"

# Mesos credentials directory
mesos_credentials_dir: /srv/mesos

# List (either plain text or JSON) of accepted credentials
mesos_credentials_file: "{{mesos_credentials_dir}}/credentials"

# Mesos slave credential directory
mesos_slave_credential_dir: "{{mesos_credentials_dir}}/agent"

# Credential used to identify the slave to the master
mesos_slave_credential_file: "{{mesos_slave_credential_dir}}/credential"

# Default Mesos attributes
mesos_attributes: ""